### ISSUE TITLE
Reverse order of items

### ISSUE THREAD

**Issue by asdoi** [gildesmarais/html2rss#80]
In my case the website I want to parse to RSS adds their newest items to the end of the site.
So if I create the RSS Feed the oldest article is at the top and the newest one at the end.
I already searched for a command to reverse the order a scope through the CSS selector but I did not found one.
It would be nice if a reverse parameter could be added to the parse methods.
Thank you in advance

**Comment by gildesmarais** [comment]
Hey,

I was thinking about this enhancement. The RSS 2.0 spec says, that the order of items must not be relevant. However, that spec is very controversial, quite dated and I see your use case.

I'll think of a way to specify the order on the items. Probably just an `order` key in the `items` selector. :)

I don't know when I'll be able to implement it, but I'll let you know. If someone else would like to implement it, give me a ping to prevent duplicate work, please. :)

Cheers!

**Comment by gildesmarais** [comment]
Was able to squeeze the feature in today. :) Will be working on new release version.

**Comment by gildesmarais** [comment]
[html2rss v0.9.0](https://rubygems.org/gems/html2rss/versions/0.9.0) is out in the wild.

**Comment by asdoi** [comment]
Thank you very much. Works perfectly :+1:
